### ISSUE TITLE
invalid character 'N' looking for beginning of value

### ISSUE THREAD

**Issue by deepy** [jgsqware/clairctl#130]
> Clairctl version 1.2.8

Using `clairctl report nexus-stage.localnet.com/user/rpublisher` I get the following

```
clairctl report nexus-stage.localnet.com/user/rpublisher
2018-09-26 11:08:56.207922 E | clair: analysing layer [sha256:3693a] 1/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.208622 E | clair: analysing layer [sha256:deaaf] 2/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.209222 E | clair: analysing layer [sha256:06d26] 3/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.209824 E | clair: analysing layer [sha256:e35ad] 4/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.210723 E | clair: analysing layer [sha256:d5c32] 5/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.211519 E | clair: analysing layer [sha256:772a9] 6/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.212118 E | clair: analysing layer [sha256:ec3f7] 7/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.212715 E | clair: analysing layer [sha256:6bd94] 8/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.213244 E | clair: analysing layer [sha256:c581a] 9/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.213764 E | clair: analysing layer [sha256:0fb63] 10/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.214334 E | clair: analysing layer [sha256:19ab4] 11/12: reading layer analysis: invalid character 'N' looking for beginning of value
2018-09-26 11:08:56.214892 E | clair: analysing layer [sha256:05d1a] 12/12: reading layer analysis: invalid character 'N' looking for beginning of value
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 1 [running]:
text/template.errRecover(0xc4205c7930)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/text/template/exec.go:140 +0x1ec
panic(0x9c7120, 0xf470e0)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/jgsqware/clairctl/clair.allVulnerabilities(0xc420360a00, 0x18, 0xc420112d50, 0x2d, 0xc420360a2e, 0x6, 0xfbabd0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/jgsqware/clairctl/clair/report.go:90 +0x29c
reflect.Value.call(0x9a0920, 0xa9af50, 0x13, 0xa6f58e, 0x4, 0xc42033ad60, 0x1, 0x1, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x9a0920, 0xa9af50, 0x13, 0xc42033ad60, 0x1, 0x1, 0xf6cc00, 0xc4202660c0, 0xa29d00)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/reflect/value.go:302 +0xa4
text/template.(*state).evalCall(0xc4205c78b0, 0xa29d00, 0xc420356c30, 0x99, 0x9a0920, 0xa9af50, 0x13, 0xf6c720, 0xc420266030, 0xc4201a6a50, ...)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/text/template/exec.go:668 +0x51f
text/template.(*state).evalFunction(0xc4205c78b0, 0xa29d00, 0xc420356c30, 0x99, 0xc420266060, 0xf6c720, 0xc420266030, 0xc42033aaa0, 0x2, 0x2, ...)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/text/template/exec.go:536 +0x18e
text/template.(*state).evalCommand(0xc4205c78b0, 0xa29d00, 0xc420356c30, 0x99, 0xc420266030, 0x0, 0x0, 0x0, 0x1, 0x3, ...)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/text/template/exec.go:433 +0x6cd
text/template.(*state).evalPipeline(0xc4205c78b0, 0xa29d00, 0xc420356c30, 0x99, 0xc4203566e0, 0xa29d00, 0xc420356c30, 0x2a0f)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/text/template/exec.go:406 +0xf2
text/template.(*state).walkIfOrWith(0xc4205c78b0, 0x13, 0xa29d00, 0xc420356c30, 0x99, 0xc4203566e0, 0xc4202660f0, 0x0)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/text/template/exec.go:261 +0xbc
text/template.(*state).walk(0xc4205c78b0, 0xa29d00, 0xc420356c30, 0x99, 0xf6cc60, 0xc4201e05c0)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/text/template/exec.go:251 +0x2ff
text/template.(*state).walk(0xc4205c78b0, 0xa29d00, 0xc420356c30, 0x99, 0xf6c900, 0xc420112f30)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/text/template/exec.go:240 +0x139
text/template.(*Template).execute(0xc4203e89c0, 0xf62840, 0xc4201097a0, 0xa29d00, 0xc420356c30, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/text/template/exec.go:195 +0x20a
text/template.(*Template).Execute(0xc4203e89c0, 0xf62840, 0xc4201097a0, 0xa29d00, 0xc420356c30, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/text/template/exec.go:178 +0x53
github.com/jgsqware/clairctl/clair.ReportAsHTML(0xc420360a00, 0x18, 0xc420112d50, 0x2d, 0xc420360a2e, 0x6, 0xfbabd0, 0x0, 0x0, 0x6, ...)
        /home/travis/gopath/src/github.com/jgsqware/clairctl/clair/report.go:41 +0x426
github.com/jgsqware/clairctl/cmd.glob..func6(0xf58280, 0xc42035c130, 0x1, 0x1)
        /home/travis/gopath/src/github.com/jgsqware/clairctl/cmd/report.go:42 +0x7eb
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).execute(0xf58280, 0xc42035c0e0, 0x1, 0x1, 0xf58280, 0xc42035c0e0)
        /home/travis/gopath/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:636 +0x231
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xf584a0, 0xc4201aff78, 0x4066bc, 0xc420072058)
        /home/travis/gopath/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).Execute(0xf584a0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/jgsqware/clairctl/cmd.Execute()
        /home/travis/gopath/src/github.com/jgsqware/clairctl/cmd/root.go:32 +0x31
main.main()
        /home/travis/gopath/src/github.com/jgsqware/clairctl/main.go:20 +0x20
```

**Comment by deepy** [comment]
Same issue if I'm doing `-l`

**Comment by deepy** [comment]
Nevermind, using clair instead of clair-git this works better.
