### ISSUE TITLE
Error while trying to get report for a given docker image from registry

### ISSUE THREAD

**Issue by umanam** [jgsqware/clairctl#78]
Error while trying to get clairctl report for given docker image from registry.

docker-compose exec clairctl clairctl report sonatype/nexus@sha256:1165b311d447bda4618cc60c646172968e5c6d2e1123878564de98299752d899 --log-level debug
2017-08-07 15:56:24.108386 D | config: Using config file: /home/clairctl/clairctl.yml
2017-08-07 15:56:24.108634 D | dockerdist: Downloading manifest for sonatype/nexus@sha256:1165b311d447bda4618cc60c646172968e5c6d2e1123878564de98299752d899
panic: interface conversion: *reference.canonicalRef is not reference.NamedTagged: missing method Tag

goroutine 1 [running]:
panic(0x7efd67104780, 0xc4203ce780)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/jgsqware/clairctl/docker/dockerdist.DownloadManifest(0x7ffd2a658ed5, 0x56, 0xc4201d7901, 0x7efd6689be22, 0x7efd670c8900, 0xc4201d7a78, 0xc4203d47c0, 0xc4201d7ae0, 0x7efd66b8cf96)
	/go/src/github.com/jgsqware/clairctl/docker/dockerdist/dockerdist.go:214 +0x1c4
github.com/jgsqware/clairctl/docker.RetrieveManifest(0x7ffd2a658ed5, 0x56, 0x1, 0x0, 0xc4203bfb00, 0xe0ff5cb400000013, 0xc4201d7a30, 0x7efd6689f365, 0xc4203d47c0)
	/go/src/github.com/jgsqware/clairctl/docker/docker.go:21 +0xbe
github.com/jgsqware/clairctl/cmd.glob..func6(0x7efd67406fc0, 0xc4203c65a0, 0x1, 0x3)
	/go/src/github.com/jgsqware/clairctl/cmd/report.go:27 +0xc9
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).execute(0x7efd67406fc0, 0xc4203c6450, 0x3, 0x3, 0x7efd67406fc0, 0xc4203c6450)
	/go/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:636 +0x445
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x7efd674071e0, 0xc4201d7ee8, 0x7efd6689385d, 0xc42000e0b8)
	/go/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:722 +0x369
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).Execute(0x7efd674071e0, 0x7efd67407400, 0x0)
	/go/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:681 +0x2d
github.com/jgsqware/clairctl/cmd.Execute()
	/go/src/github.com/jgsqware/clairctl/cmd/root.go:32 +0x3b
main.main()
	/go/src/github.com/jgsqware/clairctl/main.go:20 +0x16

**Comment by SerialVelocity** [comment]
This is because clairctl doesn't seem to support referencing images by sha256sum. It works if you use a tag
