### ISSUE TITLE
Getting segmentation fault

### ISSUE THREAD

**Issue by pramodhkp** [jgsqware/clairctl#97]
```
centos@docker-security ~]$ clairctl push -l registry.access.redhat.com/rhel7
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x518490]

goroutine 1 [running]:
net/url.(*URL).String(0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/url/url.go:726 +0x40
github.com/jgsqware/clairctl/clair.insertRegistryMapping(0xc42020f7c7, 0x40, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/clair/push.go:129 +0x7a
github.com/jgsqware/clairctl/clair.(*layering).pushAll(0xc42020f8b0, 0xc420131480, 0x1)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/clair/layering.go:53 +0x2d0
github.com/jgsqware/clairctl/clair.Push(0x21ffe60, 0xc4201cfd80, 0x21f4c40, 0xc42021e0b0, 0xc4201cfd80, 0x21f4c40)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/clair/push.go:39 +0x40f
github.com/jgsqware/clairctl/cmd.glob..func9(0x21dd920, 0xc4203ee7c0, 0x1, 0x2)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/cmd/push.go:34 +0x258
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).execute(0x21dd920, 0xc4203ee2a0, 0x2, 0x2, 0x21dd920, 0xc4203ee2a0)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:636 +0x231
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x21ddd60, 0xc420537f78, 0x40677c, 0xc42001a0b8)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).Execute(0x21ddd60, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/jgsqware/clairctl/cmd.Execute()
	/home/travis/gopath/src/github.com/jgsqware/clairctl/cmd/root.go:32 +0x31
main.main()
	/home/travis/gopath/src/github.com/jgsqware/clairctl/main.go:20 +0x20
```

Getting segementation fault when trying to push image to clair.

Other info:
```
[centos@docker-security ~]$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```

Fetched from master
```
[centos@docker-security ~]$ clairctl version

Clairctl version 1.2.8
```

**Comment by jdel** [comment]
Any chance you could try to run this with root access like described in #98 ?
