### ISSUE TITLE
Segmentation fault on analyzing local image

### ISSUE THREAD

**Issue by mkauzlar** [jgsqware/clairctl#98]
./clairctl-linux-amd64 analyze --local image:tag
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f6a30]

goroutine 1 [running]:
net/url.(*URL).String(0x0, 0x20, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/url/url.go:726 +0x40
github.com/jgsqware/clairctl/clair.insertRegistryMapping(0xc420057407, 0x40, 0xc420360b40, 0x20)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/clair/push.go:128 +0x7a
github.com/jgsqware/clairctl/clair.(*layering).pushAll(0xc4200579a0, 0xc420018d00, 0x8)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/clair/layering.go:53 +0x2d0
github.com/jgsqware/clairctl/clair.Push(0xf6d200, 0xc420350e90, 0xf689c0, 0xc4201b2000, 0xc420350e90, 0xf689c0)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/clair/push.go:39 +0x40f
github.com/jgsqware/clairctl/cmd.glob..func1(0xf577e0, 0xc4203622e0, 0x1, 0x2)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/cmd/analyze.go:49 +0x270
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).execute(0xf577e0, 0xc4203620e0, 0x2, 0x2, 0xf577e0, 0xc4203620e0)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:636 +0x231
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xf584a0, 0xc4201a3f78, 0x4066bc, 0xc420060058)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra.(*Command).Execute(0xf584a0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jgsqware/clairctl/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/jgsqware/clairctl/cmd.Execute()
	/home/travis/gopath/src/github.com/jgsqware/clairctl/cmd/root.go:32 +0x31
main.main()
	/home/travis/gopath/src/github.com/jgsqware/clairctl/main.go:20 +0x20

**Comment by mkauzlar** [comment]
This must be a permission issue because running the command as root works fine
